### PR TITLE
Fix GitHub Enterprise URL building

### PR DESCRIPTION
**Pull request by edubxb**

### CODE REVIEW

**Comment by freaktechnik** [comment]
oh... I'll try to get this in tomorrow morning!

**Comment by edubxb** [comment]
Seems that the latest version works without this change, so I will close this PR.

**Comment by freaktechnik** [comment]
Might still be a good idea to merge it, though the default params are in theory never hit for enterprise installs from what I recall.

**Comment by freaktechnik** [comment]
And thank you again for testing things and yay for it finally working!

**Pull request merged**
